import sizes, { screenHeight, screenWidth, sizesTablet, useDimensions } from './size/sizes';
import { Style } from './style/styleSheet';

const fonts = {
	regular: 'DMSans-Regular',
	medium: 'DMSans-Medium',
	bold: 'DMSans-Bold',
};

const images = {
	no_img_uri:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png',
	bg_header_left: require('./image/bg_header_left.png'),
	bg_header_right: require('./image/bg_header_right.png'),
	bg_header_left2: require('./image/bg_header_left2.png'),
	bg_header_left3: require('./image/bg_header_left3.png'),
	ic_liveme: require('./image/ic_liveme.png'),
	ic_profile: require('./image/ic_profile.png'),
	ic_profile_active: require('./image/ic_profile_active.png'),
	ic_my_request: require('./image/ic_my_request.png'),
	ic_my_request_active: require('./image/ic_my_request_active.png'),
	ic_add_plus: require('./image/ic_add_plus.png'),
	ic_add_plus_active: require('./image/ic_add_plus_active.png'),
	ic_heart: require('./image/ic_heart.png'),
	ic_heart_active: require('./image/ic_heart_active.png'),
	ic_search: require('./image/ic_search.png'),
	ic_search2: require('./image/ic_search2.png'),
	ic_search_active: require('./image/ic_search_active.png'),
	ic_eye: require('./image/ic_eye.png'),
	ic_eye_close: require('./image/ic_eye_close.png'),
	ic_wallet: require('./image/ic_wallet.png'),
	ic_back: require('./image/ic_back.png'),
	ic_clear: require('./image/ic_clear.png'),
	img_media: require('./image/img_media.png'),
	ic_filter_live: require('./image/ic_filter_live.png'),
	ic_filter_video: require('./image/ic_filter_video.png'),
	ic_filter_picture: require('./image/ic_filter_picture.png'),
	ic_star: require('./image/ic_star.png'),
	ic_user: require('./image/ic_user.png'),
	ic_lock: require('./image/ic_lock.png'),
	ic_google: require('./image/ic_google.png'),
	ic_facebook: require('./image/ic_facebook.png'),
	ic_close: require('./image/ic_close.png'),
	ic_close2: require('./image/ic_close2.png'),
	ic_close48: require('./image/ic_close48.png'),
	ic_congrat: require('./image/ic_congrat.png'),
	ic_check: require('./image/ic_check.png'),
	ic_arrow_down: require('./image/ic_arrow_down.png'),
	ic_arrow_right: require('./image/ic_arrow_right.png'),
	ic_clock: require('./image/ic_clock.png'),
	ic_album: require('./image/ic_album.png'),
	ic_map: require('./image/ic_map.png'),
	ic_like: require('./image/ic_like.png'),
	ic_unlike: require('./image/ic_unlike.png'),
	ic_external: require('./image/ic_external.png'),
	ic_timer: require('./image/ic_timer.png'),
	ic_circle_red: require('./image/ic_circle_red.png'),
	ic_changepasssuccess: require('./image/ic_changepasssuccess.png'),
	ic_radio_uncheck: require('./image/ic_radio_uncheck.png'),
	ic_radio_checked: require('./image/ic_radio_checked.png'),
	ic_checkbox_checked: require('./image/ic_checkbox_checked.png'),
	ic_checkbox_uncheck: require('./image/ic_checkbox_uncheck.png'),
	ic_info: require('./image/ic_info.png'),
	ic_filter_favourite: require('./image/ic_filter_favourite.png'),
	ic_error: require('./image/ic_error.png'),
	ic_camera: require('./image/ic_camera.png'),
	ic_star_unrate: require('./image/ic_star_unrate.png'),
	ic_star_rated: require('./image/ic_star_rated.png'),
	ic_star_mini: require('./image/ic_star_mini.png'),
	ic_edit: require('./image/ic_edit.png'),
	cvv: require('./image/cvv.png'),
	ic_success_payment: require('./image/ic_success_payment.png'),
	ic_fail_payment: require('./image/ic_fail_payment.png'),
	ic_trash: require('./image/ic_trash.png'),
	ic_credit_card: require('./image/ic_credit_card.png'),
	ic_success_withdraw: require('./image/ic_success_withdraw.png'),
	ic_send: require('./image/ic_send.png'),
	ic_warning: require('./image/ic_warning.png'),
	ic_succes_change_phone: require('./image/ic_succes_change_phone.png'),
	star_rated: require('./image/star_rated.png'),
	star_unrate: require('./image/star_unrate.png'),
	ic_download: require('./image/ic_download.png'),
	ic_marker: require('./image/ic_marker.png'),
	ic_completed: require('./image/ic_completed.png'),
	ic_close_camera: require('./image/ic_close_camera.png'),
	ic_switch_camera: require('./image/ic_switch_camera.png'),
	ic_downloading: require('./image/ic_downloading.png'),
	ic_apple: require('./image/ic_apple.png'),
	ic_mail: require('./image/Mail.png'),
	ic_card_user: require('./image/ic_card_user.png'),
	onboarding1: require('./image/onboarding1.png'),
	onboarding2: require('./image/onboarding2.png'),
	onboarding3: require('./image/onboarding3.png'),
	ic_home_active: require('./image/ic_home_active.png'),
	ic_home: require('./image/ic_home.png'),
	ic_selected: require('./image/ic_selected.png'),
};

const colors = {
	white: '#FFFFFF',
	black: '#212B36',
	bgTransparent: '#00000030',
	disable: '#F0F7FF',
	//Accent Colors
	primary: '#3772FF',
	primary300: '#8AB5FF',
	primary400: '#6196FF',
	primary100: '#DBEBFF',
	primary50: '#F0F7FF',
	red: '#FF6F5C',
	warning: '#FFB235',
	yellowBG: '#FFF6E3',
	errorBG: '#FFEFED',
	success: '#1E9E75',
	error: '#E4513D',
	//Netrual Colors
	secondary_text: '#637381',
	title: '#212B36',
	primary_text: '#454F5B',
	disable_text: '#919EAB',
	border: '#C4CDD5',
	dividers: '#DFE3E8',
	background: '#F4F6F8',
	background_gray: '#F9FAFB',
};

export {
	colors,
	fonts,
	images,
	screenHeight,
	screenWidth,
	sizes,
	sizesTablet,
	Style,
	useDimensions,
};
